### ISSUE TITLE
Errors occurred during training on two GPUs.

### ISSUE THREAD

**Issue by Er-gou123** [ZGC-LLM-Safety/TrafficLLM#16]
I have modified the trafficllm_stage1.sh file as follows:
PRE_SEQ_LEN=128
LR=2e-2
NUM_GPUS=2
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \
    --do_train \
    --train_file ../datasets/instructions/instructions.json \
    --validation_file ../datasets/instructions/instructions.json \
    --preprocessing_num_workers 10 \
    --prompt_column instruction \
    --response_column output \
    --overwrite_cache \
    --cache_dir ../cache \
    --model_name_or_path ../models/chatglm2/chatglm2-6b \
    --output_dir ../models/chatglm2/peft/instruction \
    --overwrite_output_dir \
    --max_source_length 1024 \
    --max_target_length 32 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 20000 \
    --logging_steps 10 \
    --save_steps 4000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN
    

and I have eight GPUs in one machine，pytorch version is 2.0，but when i run ./trafficllm_stage1.sh, it get error.And it can run in one gup.The error information as follow:

Traceback (most recent call last):
  File "/data/cyh/TrafficLLM/dual-stage-tuning/main.py", line 416, in <module>
    main()
  File "/data/cyh/TrafficLLM/dual-stage-tuning/main.py", line 233, in main
    with training_args.main_process_first(desc="train dataset map pre-processing"):
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/site-packages/transformers/training_args.py", line 1961, in main_process_first
    torch.distributed.barrier()
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3313, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 4d000
Traceback (most recent call last):
  File "/data/cyh/TrafficLLM/dual-stage-tuning/main.py", line 416, in <module>
    main()
  File "/data/cyh/TrafficLLM/dual-stage-tuning/main.py", line 234, in main
    train_dataset = train_dataset.map(
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/site-packages/transformers/training_args.py", line 1972, in main_process_first
    torch.distributed.barrier()
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3313, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 4d000
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 698543) of binary: /data/cyh/anaconda3/envs/trafficllm/bin/python
Traceback (most recent call last):
  File "/data/cyh/anaconda3/envs/trafficllm/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/cyh/anaconda3/envs/trafficllm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

Is there any detail I might have overlooked in the multi-GPU training task?

**Comment by XGBoost** [comment]
@Er-gou123 GitHub indicates that the repository's bandwidth quota has been exhausted, preventing some model files from being downloaded. Would it be possible for you to share a version of the code with the model files already downloaded? Thank you!
My email is: [hust953455615@163.com](mailto:hust953455615@163.com)
